version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: . 
    container_name: nestjs-app
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000" 
    depends_on:
      - db 
    volumes:
      - .:/app 

volumes:
  postgres-data:
