version: '3.8'

services:
  db:
    image: postgres:14 
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin          
      POSTGRES_PASSWORD: Admin@1234!     
      POSTGRES_DB: techmaint_solutions 
    ports:
      - "5432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data 


volumes:
  postgres-data:  

